//mod print;
//mod vars;
// mod string;
// mod types;
// mod arrays;
// mod tuples;
// mod vectors;
// mod conditionals;
// mod loops;
// mod functions;
// mod pointer_ref;
// mod structs;
// mod struct_function;
// mod enums;
mod cli_args;
fn main() {
    //print::run();
    //vars::run();
    // types::run();
    // string::run();
    // tuples::run();
    // arrays::run();
    // vectors::run();
    // conditionals::run();
    // loops::run();
    // functions::run();
    // pointer_ref::run();
    // structs::run();
    // struct_function::run();
    // enums::run();
    cli_args::run();
}
